spring.application.name=backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/galleria_bank
spring.datasource.username=postgres
spring.datasource.password=postgres

api.security.token.private=classpath:keys/private.pem
api.security.token.public=classpath:keys/public.pem
